### ISSUE TITLE
Cannot include text "{}" with `--inline`

### ISSUE THREAD

**Issue by SnoringFrog** [jonhiggs/cecho#1]
When using `--inline`, empty braces can't be contained in the output.
![screen shot 2015-10-09 at 2 40 28 pm](https://cloud.githubusercontent.com/assets/3333002/10402537/f862ca14-6e93-11e5-8d8c-8179fb04b405.png)

**Comment by jonhiggs** [comment]
Thanks for your PR. I've merged it in and also had more of a look of the osx/linux compatibility. I've setup TravisCI to run the tests on Linux to help avoid any regression.
